/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminTelefonesRouteImport } from './routes/admin.telefones'
import { Route as AdminSegurancaRouteImport } from './routes/admin.seguranca'
import { Route as AdminPesquisasRouteImport } from './routes/admin.pesquisas'
import { Route as AdminLojasRouteImport } from './routes/admin.lojas'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminEventosRouteImport } from './routes/admin.eventos'
import { Route as AdminDenunciasRouteImport } from './routes/admin.denuncias'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AuthenticatedTransporteRouteImport } from './routes/_authenticated.transporte'
import { Route as AuthenticatedSosRouteImport } from './routes/_authenticated.sos'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated.perfil'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated.pedidos'
import { Route as AuthenticatedMinhaLojaRouteImport } from './routes/_authenticated.minha-loja'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedComunidadeRouteImport } from './routes/_authenticated.comunidade'
import { Route as AuthenticatedComercioRouteImport } from './routes/_authenticated.comercio'
import { Route as AuthenticatedCarrinhoRouteImport } from './routes/_authenticated.carrinho'
import { Route as AuthenticatedPedidosPedidoIdRouteImport } from './routes/_authenticated.pedidos.$pedidoId'
import { Route as AuthenticatedPedidoConfirmadoPedidoIdRouteImport } from './routes/_authenticated.pedido-confirmado.$pedidoId'
import { Route as AuthenticatedComercioProdutoProdutoIdRouteImport } from './routes/_authenticated.comercio.produto.$produtoId'
import { Route as AuthenticatedComercioLojaLojaIdRouteImport } from './routes/_authenticated.comercio.loja.$lojaId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTelefonesRoute = AdminTelefonesRouteImport.update({
  id: '/telefones',
  path: '/telefones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSegurancaRoute = AdminSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPesquisasRoute = AdminPesquisasRouteImport.update({
  id: '/pesquisas',
  path: '/pesquisas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojasRoute = AdminLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventosRoute = AdminEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDenunciasRoute = AdminDenunciasRouteImport.update({
  id: '/denuncias',
  path: '/denuncias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedTransporteRoute = AuthenticatedTransporteRouteImport.update({
  id: '/transporte',
  path: '/transporte',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSosRoute = AuthenticatedSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMinhaLojaRoute = AuthenticatedMinhaLojaRouteImport.update({
  id: '/minha-loja',
  path: '/minha-loja',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComunidadeRoute = AuthenticatedComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComercioRoute = AuthenticatedComercioRouteImport.update({
  id: '/comercio',
  path: '/comercio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCarrinhoRoute = AuthenticatedCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPedidosPedidoIdRoute =
  AuthenticatedPedidosPedidoIdRouteImport.update({
    id: '/$pedidoId',
    path: '/$pedidoId',
    getParentRoute: () => AuthenticatedPedidosRoute,
  } as any)
const AuthenticatedPedidoConfirmadoPedidoIdRoute =
  AuthenticatedPedidoConfirmadoPedidoIdRouteImport.update({
    id: '/pedido-confirmado/$pedidoId',
    path: '/pedido-confirmado/$pedidoId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComercioProdutoProdutoIdRoute =
  AuthenticatedComercioProdutoProdutoIdRouteImport.update({
    id: '/produto/$produtoId',
    path: '/produto/$produtoId',
    getParentRoute: () => AuthenticatedComercioRoute,
  } as any)
const AuthenticatedComercioLojaLojaIdRoute =
  AuthenticatedComercioLojaLojaIdRouteImport.update({
    id: '/loja/$lojaId',
    path: '/loja/$lojaId',
    getParentRoute: () => AuthenticatedComercioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/carrinho': typeof AuthenticatedCarrinhoRoute
  '/comercio': typeof AuthenticatedComercioRouteWithChildren
  '/comunidade': typeof AuthenticatedComunidadeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/minha-loja': typeof AuthenticatedMinhaLojaRoute
  '/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/sos': typeof AuthenticatedSosRoute
  '/transporte': typeof AuthenticatedTransporteRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/pesquisas': typeof AdminPesquisasRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/telefones': typeof AdminTelefonesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/pedido-confirmado/$pedidoId': typeof AuthenticatedPedidoConfirmadoPedidoIdRoute
  '/pedidos/$pedidoId': typeof AuthenticatedPedidosPedidoIdRoute
  '/comercio/loja/$lojaId': typeof AuthenticatedComercioLojaLojaIdRoute
  '/comercio/produto/$produtoId': typeof AuthenticatedComercioProdutoProdutoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/carrinho': typeof AuthenticatedCarrinhoRoute
  '/comercio': typeof AuthenticatedComercioRouteWithChildren
  '/comunidade': typeof AuthenticatedComunidadeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/minha-loja': typeof AuthenticatedMinhaLojaRoute
  '/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/sos': typeof AuthenticatedSosRoute
  '/transporte': typeof AuthenticatedTransporteRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/pesquisas': typeof AdminPesquisasRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/telefones': typeof AdminTelefonesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin': typeof AdminIndexRoute
  '/pedido-confirmado/$pedidoId': typeof AuthenticatedPedidoConfirmadoPedidoIdRoute
  '/pedidos/$pedidoId': typeof AuthenticatedPedidosPedidoIdRoute
  '/comercio/loja/$lojaId': typeof AuthenticatedComercioLojaLojaIdRoute
  '/comercio/produto/$produtoId': typeof AuthenticatedComercioProdutoProdutoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/carrinho': typeof AuthenticatedCarrinhoRoute
  '/_authenticated/comercio': typeof AuthenticatedComercioRouteWithChildren
  '/_authenticated/comunidade': typeof AuthenticatedComunidadeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/minha-loja': typeof AuthenticatedMinhaLojaRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/sos': typeof AuthenticatedSosRoute
  '/_authenticated/transporte': typeof AuthenticatedTransporteRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/denuncias': typeof AdminDenunciasRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/lojas': typeof AdminLojasRoute
  '/admin/pesquisas': typeof AdminPesquisasRoute
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/telefones': typeof AdminTelefonesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/pedido-confirmado/$pedidoId': typeof AuthenticatedPedidoConfirmadoPedidoIdRoute
  '/_authenticated/pedidos/$pedidoId': typeof AuthenticatedPedidosPedidoIdRoute
  '/_authenticated/comercio/loja/$lojaId': typeof AuthenticatedComercioLojaLojaIdRoute
  '/_authenticated/comercio/produto/$produtoId': typeof AuthenticatedComercioProdutoProdutoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/reset-password'
    | '/carrinho'
    | '/comercio'
    | '/comunidade'
    | '/dashboard'
    | '/minha-loja'
    | '/pedidos'
    | '/perfil'
    | '/sos'
    | '/transporte'
    | '/admin/banners'
    | '/admin/denuncias'
    | '/admin/eventos'
    | '/admin/financeiro'
    | '/admin/lojas'
    | '/admin/pesquisas'
    | '/admin/seguranca'
    | '/admin/telefones'
    | '/admin/usuarios'
    | '/admin/'
    | '/pedido-confirmado/$pedidoId'
    | '/pedidos/$pedidoId'
    | '/comercio/loja/$lojaId'
    | '/comercio/produto/$produtoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/carrinho'
    | '/comercio'
    | '/comunidade'
    | '/dashboard'
    | '/minha-loja'
    | '/pedidos'
    | '/perfil'
    | '/sos'
    | '/transporte'
    | '/admin/banners'
    | '/admin/denuncias'
    | '/admin/eventos'
    | '/admin/financeiro'
    | '/admin/lojas'
    | '/admin/pesquisas'
    | '/admin/seguranca'
    | '/admin/telefones'
    | '/admin/usuarios'
    | '/admin'
    | '/pedido-confirmado/$pedidoId'
    | '/pedidos/$pedidoId'
    | '/comercio/loja/$lojaId'
    | '/comercio/produto/$produtoId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/carrinho'
    | '/_authenticated/comercio'
    | '/_authenticated/comunidade'
    | '/_authenticated/dashboard'
    | '/_authenticated/minha-loja'
    | '/_authenticated/pedidos'
    | '/_authenticated/perfil'
    | '/_authenticated/sos'
    | '/_authenticated/transporte'
    | '/admin/banners'
    | '/admin/denuncias'
    | '/admin/eventos'
    | '/admin/financeiro'
    | '/admin/lojas'
    | '/admin/pesquisas'
    | '/admin/seguranca'
    | '/admin/telefones'
    | '/admin/usuarios'
    | '/admin/'
    | '/_authenticated/pedido-confirmado/$pedidoId'
    | '/_authenticated/pedidos/$pedidoId'
    | '/_authenticated/comercio/loja/$lojaId'
    | '/_authenticated/comercio/produto/$produtoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/telefones': {
      id: '/admin/telefones'
      path: '/telefones'
      fullPath: '/admin/telefones'
      preLoaderRoute: typeof AdminTelefonesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seguranca': {
      id: '/admin/seguranca'
      path: '/seguranca'
      fullPath: '/admin/seguranca'
      preLoaderRoute: typeof AdminSegurancaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pesquisas': {
      id: '/admin/pesquisas'
      path: '/pesquisas'
      fullPath: '/admin/pesquisas'
      preLoaderRoute: typeof AdminPesquisasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lojas': {
      id: '/admin/lojas'
      path: '/lojas'
      fullPath: '/admin/lojas'
      preLoaderRoute: typeof AdminLojasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/denuncias': {
      id: '/admin/denuncias'
      path: '/denuncias'
      fullPath: '/admin/denuncias'
      preLoaderRoute: typeof AdminDenunciasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/transporte': {
      id: '/_authenticated/transporte'
      path: '/transporte'
      fullPath: '/transporte'
      preLoaderRoute: typeof AuthenticatedTransporteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sos': {
      id: '/_authenticated/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof AuthenticatedSosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minha-loja': {
      id: '/_authenticated/minha-loja'
      path: '/minha-loja'
      fullPath: '/minha-loja'
      preLoaderRoute: typeof AuthenticatedMinhaLojaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comunidade': {
      id: '/_authenticated/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof AuthenticatedComunidadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comercio': {
      id: '/_authenticated/comercio'
      path: '/comercio'
      fullPath: '/comercio'
      preLoaderRoute: typeof AuthenticatedComercioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/carrinho': {
      id: '/_authenticated/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof AuthenticatedCarrinhoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pedidos/$pedidoId': {
      id: '/_authenticated/pedidos/$pedidoId'
      path: '/$pedidoId'
      fullPath: '/pedidos/$pedidoId'
      preLoaderRoute: typeof AuthenticatedPedidosPedidoIdRouteImport
      parentRoute: typeof AuthenticatedPedidosRoute
    }
    '/_authenticated/pedido-confirmado/$pedidoId': {
      id: '/_authenticated/pedido-confirmado/$pedidoId'
      path: '/pedido-confirmado/$pedidoId'
      fullPath: '/pedido-confirmado/$pedidoId'
      preLoaderRoute: typeof AuthenticatedPedidoConfirmadoPedidoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comercio/produto/$produtoId': {
      id: '/_authenticated/comercio/produto/$produtoId'
      path: '/produto/$produtoId'
      fullPath: '/comercio/produto/$produtoId'
      preLoaderRoute: typeof AuthenticatedComercioProdutoProdutoIdRouteImport
      parentRoute: typeof AuthenticatedComercioRoute
    }
    '/_authenticated/comercio/loja/$lojaId': {
      id: '/_authenticated/comercio/loja/$lojaId'
      path: '/loja/$lojaId'
      fullPath: '/comercio/loja/$lojaId'
      preLoaderRoute: typeof AuthenticatedComercioLojaLojaIdRouteImport
      parentRoute: typeof AuthenticatedComercioRoute
    }
  }
}

interface AuthenticatedComercioRouteChildren {
  AuthenticatedComercioLojaLojaIdRoute: typeof AuthenticatedComercioLojaLojaIdRoute
  AuthenticatedComercioProdutoProdutoIdRoute: typeof AuthenticatedComercioProdutoProdutoIdRoute
}

const AuthenticatedComercioRouteChildren: AuthenticatedComercioRouteChildren = {
  AuthenticatedComercioLojaLojaIdRoute: AuthenticatedComercioLojaLojaIdRoute,
  AuthenticatedComercioProdutoProdutoIdRoute:
    AuthenticatedComercioProdutoProdutoIdRoute,
}

const AuthenticatedComercioRouteWithChildren =
  AuthenticatedComercioRoute._addFileChildren(
    AuthenticatedComercioRouteChildren,
  )

interface AuthenticatedPedidosRouteChildren {
  AuthenticatedPedidosPedidoIdRoute: typeof AuthenticatedPedidosPedidoIdRoute
}

const AuthenticatedPedidosRouteChildren: AuthenticatedPedidosRouteChildren = {
  AuthenticatedPedidosPedidoIdRoute: AuthenticatedPedidosPedidoIdRoute,
}

const AuthenticatedPedidosRouteWithChildren =
  AuthenticatedPedidosRoute._addFileChildren(AuthenticatedPedidosRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCarrinhoRoute: typeof AuthenticatedCarrinhoRoute
  AuthenticatedComercioRoute: typeof AuthenticatedComercioRouteWithChildren
  AuthenticatedComunidadeRoute: typeof AuthenticatedComunidadeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMinhaLojaRoute: typeof AuthenticatedMinhaLojaRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedSosRoute: typeof AuthenticatedSosRoute
  AuthenticatedTransporteRoute: typeof AuthenticatedTransporteRoute
  AuthenticatedPedidoConfirmadoPedidoIdRoute: typeof AuthenticatedPedidoConfirmadoPedidoIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCarrinhoRoute: AuthenticatedCarrinhoRoute,
  AuthenticatedComercioRoute: AuthenticatedComercioRouteWithChildren,
  AuthenticatedComunidadeRoute: AuthenticatedComunidadeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMinhaLojaRoute: AuthenticatedMinhaLojaRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedSosRoute: AuthenticatedSosRoute,
  AuthenticatedTransporteRoute: AuthenticatedTransporteRoute,
  AuthenticatedPedidoConfirmadoPedidoIdRoute:
    AuthenticatedPedidoConfirmadoPedidoIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminDenunciasRoute: typeof AdminDenunciasRoute
  AdminEventosRoute: typeof AdminEventosRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminLojasRoute: typeof AdminLojasRoute
  AdminPesquisasRoute: typeof AdminPesquisasRoute
  AdminSegurancaRoute: typeof AdminSegurancaRoute
  AdminTelefonesRoute: typeof AdminTelefonesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminDenunciasRoute: AdminDenunciasRoute,
  AdminEventosRoute: AdminEventosRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminLojasRoute: AdminLojasRoute,
  AdminPesquisasRoute: AdminPesquisasRoute,
  AdminSegurancaRoute: AdminSegurancaRoute,
  AdminTelefonesRoute: AdminTelefonesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
