/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSosRouteImport } from './routes/_authenticated.sos'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated.perfil'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedComunidadeRouteImport } from './routes/_authenticated.comunidade'
import { Route as AuthenticatedComercioRouteImport } from './routes/_authenticated.comercio'
import { Route as AuthenticatedComercioLojaLojaIdRouteImport } from './routes/_authenticated.comercio.loja.$lojaId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSosRoute = AuthenticatedSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComunidadeRoute = AuthenticatedComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComercioRoute = AuthenticatedComercioRouteImport.update({
  id: '/comercio',
  path: '/comercio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComercioLojaLojaIdRoute =
  AuthenticatedComercioLojaLojaIdRouteImport.update({
    id: '/loja/$lojaId',
    path: '/loja/$lojaId',
    getParentRoute: () => AuthenticatedComercioRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comercio': typeof AuthenticatedComercioRouteWithChildren
  '/comunidade': typeof AuthenticatedComunidadeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/sos': typeof AuthenticatedSosRoute
  '/comercio/loja/$lojaId': typeof AuthenticatedComercioLojaLojaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comercio': typeof AuthenticatedComercioRouteWithChildren
  '/comunidade': typeof AuthenticatedComunidadeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/sos': typeof AuthenticatedSosRoute
  '/comercio/loja/$lojaId': typeof AuthenticatedComercioLojaLojaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/comercio': typeof AuthenticatedComercioRouteWithChildren
  '/_authenticated/comunidade': typeof AuthenticatedComunidadeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/sos': typeof AuthenticatedSosRoute
  '/_authenticated/comercio/loja/$lojaId': typeof AuthenticatedComercioLojaLojaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comercio'
    | '/comunidade'
    | '/dashboard'
    | '/perfil'
    | '/sos'
    | '/comercio/loja/$lojaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comercio'
    | '/comunidade'
    | '/dashboard'
    | '/perfil'
    | '/sos'
    | '/comercio/loja/$lojaId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/comercio'
    | '/_authenticated/comunidade'
    | '/_authenticated/dashboard'
    | '/_authenticated/perfil'
    | '/_authenticated/sos'
    | '/_authenticated/comercio/loja/$lojaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sos': {
      id: '/_authenticated/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof AuthenticatedSosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comunidade': {
      id: '/_authenticated/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof AuthenticatedComunidadeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comercio': {
      id: '/_authenticated/comercio'
      path: '/comercio'
      fullPath: '/comercio'
      preLoaderRoute: typeof AuthenticatedComercioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comercio/loja/$lojaId': {
      id: '/_authenticated/comercio/loja/$lojaId'
      path: '/loja/$lojaId'
      fullPath: '/comercio/loja/$lojaId'
      preLoaderRoute: typeof AuthenticatedComercioLojaLojaIdRouteImport
      parentRoute: typeof AuthenticatedComercioRoute
    }
  }
}

interface AuthenticatedComercioRouteChildren {
  AuthenticatedComercioLojaLojaIdRoute: typeof AuthenticatedComercioLojaLojaIdRoute
}

const AuthenticatedComercioRouteChildren: AuthenticatedComercioRouteChildren = {
  AuthenticatedComercioLojaLojaIdRoute: AuthenticatedComercioLojaLojaIdRoute,
}

const AuthenticatedComercioRouteWithChildren =
  AuthenticatedComercioRoute._addFileChildren(
    AuthenticatedComercioRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedComercioRoute: typeof AuthenticatedComercioRouteWithChildren
  AuthenticatedComunidadeRoute: typeof AuthenticatedComunidadeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedSosRoute: typeof AuthenticatedSosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedComercioRoute: AuthenticatedComercioRouteWithChildren,
  AuthenticatedComunidadeRoute: AuthenticatedComunidadeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedSosRoute: AuthenticatedSosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
